feat(wxa): add WxaSdk, add code_to_session check_encrypted_data
ilovelll/wx-sdk pull request #1
Opened 2021-08-30 09:22 UTC by manbu-00

add WxaSdk, add code_to_session check_encrypted_data get_paid_unionid

2021-08-30 09:44 UTC, ilovelll requested changes
check the comment

2021-08-30 09:44 UTC, ilovelll commented on src/error.rs
> +pub struct ListRes<T> {
这个类型是不是当值的结果有list时候的返回？
如果没有使用，可以不加在 `error.rs` 中

2021-08-30 09:44 UTC, ilovelll commented on src/wxa.rs
> +    /// 登录时获取的 code
`WxSdk` 中 已包含了这两个字段，所以用户不必再传递这两个值

2021-08-30 09:44 UTC, ilovelll commented on src/wxa.rs
> +    pub out_trade_no: Option<String>,
我看了接口，这里需要提供 `transaction_id` 或者 `mch_id, out_trade_no` 二选一，提交之前需要校验
另外，`#[serde(default)]` 在这里作用是啥，创建时候可以忽略？

2021-08-30 09:44 UTC, ilovelll commented on src/wxa/data_analysis.rs
> +        let url = "https://api.weixin.qq.com/wxa/business/checkencryptedmsg";
这个 api 错了吧？

2021-08-30 09:44 UTC, ilovelll commented on src/wxa/data_analysis.rs
> +    pub access_token: String,
不需要

2021-09-03 02:49 UTC, manbu-00 commented on src/error.rs
> +pub struct ListRes<T> {
这个类型已经存在于 [wx_sdk/mp/datacube](https://docs.rs/wx-sdk/0.0.4/wx_sdk/mp/datacube/struct.ListRes.html)，但是我没有替换掉，希望它能更广泛的使用在项目中。而且我在 wxa 的请求（[getDailyVisitTrend](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/data-analysis/visit-trend/analysis.getDailyVisitTrend.html)）也有这个结构，所以把它放在了 `error.rs` 这里，现在几乎都把它直接当作 SdkResult（`type SdkResultList<T> = Result<ListRes<T>, SdkError>;`）。现在有个想法，就是不把它放在这里，放到 `wechat.rs`，顺便把已存在的 `SdkResult<T>` 也放过去。

2021-09-03 02:55 UTC, ilovelll commented on src/error.rs
> +pub struct ListRes<T> {
因为微信api并没有严格规范，返回中并不总是返回 list，或者说只有少数会返回 list，所以不会有这个类型
放到 `wechat.rs`，感觉也没有必要，普遍做法还是放到 `error.rs` 中，作为crate的一部分管理

2021-09-03 02:58 UTC, manbu-00 commented on src/error.rs
> +pub struct ListRes<T> {
那么就去掉好了，在具体接口再具体写出来

2021-09-03 03:08 UTC, manbu-00 commented on src/wxa.rs
> +    pub out_trade_no: Option<String>,
不想写校验，我们请求微信，然后如果参数不合适，不也是返回错误消息吗，就直接返回微信的错误信息给调用者。
`#[serde(default)]` 目的是为了前端可以不写这个属性，反序列化到后端时用默认值。

2021-09-03 07:23 UTC, ilovelll approved these changes

2021-09-03 07:27 UTC, merged